Added CPU Check

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -39,6 +39,29 @@ ui_print " ";
 show_progress 1.34 0;
 set_progress 0.8;
 
+do_cpucheck;
+do_cpucheck(){
+  test "$(file_getprop anykernel.sh do.cpucheck)" == 1 || return 1;
+  local board vendorboard platform vendorplatform cpuname match testname;
+  ui_print "Checking cpu...";
+  board=$(file_getprop /system/build.prop ro.product.board);
+  platform=$(file_getprop /system/build.prop ro.board.platform);
+  vendorboard=$(file_getprop /vendor/build.prop ro.product.board);
+  vendorplatform=$(file_getprop /vendor/build.prop ro.board.platform);
+  for testname in $(file_getprop anykernel.sh 'cpu.name.*'); do
+    for cpuname in $board $platform $vendorboard $vendorplatform; do
+      if [ "$cpuname" == "$testname" ]; then
+        ui_print "$testname" " ";
+        match=1;
+        break 2;
+      fi;
+    done;
+  done;
+  if [ ! "$match" ]; then
+    abort "Unsupported CPU. Aborting...";
+  fi;
+}
+
 file_getprop() { grep "^$2" "$1" | cut -d= -f2; }
 cleanup() { rm -rf /tmp/anykernel; }
 if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.cleanuponabort)" == 1 ]; then
